// <auto-generated />
namespace Narratives.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Objectaddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Objectaddition));
        
        string IMigrationMetadata.Id
        {
            get { return "201610250842435_Object addition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
