//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemanticsEngine.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SemanticsEngine.Tools.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string ActionType_Manual {
            get {
                return ResourceManager.GetString("ActionType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string ActionType_Special {
            get {
                return ResourceManager.GetString("ActionType_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply layer.
        /// </summary>
        internal static string SpecialAction_Apply {
            get {
                return ResourceManager.GetString("SpecialAction_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string SpecialAction_Attach {
            get {
                return ResourceManager.GetString("SpecialAction_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string SpecialAction_Connect {
            get {
                return ResourceManager.GetString("SpecialAction_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string SpecialAction_Cover {
            get {
                return ResourceManager.GetString("SpecialAction_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach.
        /// </summary>
        internal static string SpecialAction_Detach {
            get {
                return ResourceManager.GetString("SpecialAction_Detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string SpecialAction_Discard {
            get {
                return ResourceManager.GetString("SpecialAction_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string SpecialAction_Disconnect {
            get {
                return ResourceManager.GetString("SpecialAction_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string SpecialAction_Give {
            get {
                return ResourceManager.GetString("SpecialAction_Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove layer.
        /// </summary>
        internal static string SpecialAction_Remove {
            get {
                return ResourceManager.GetString("SpecialAction_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        internal static string SpecialAction_Take {
            get {
                return ResourceManager.GetString("SpecialAction_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncover.
        /// </summary>
        internal static string SpecialAction_Uncover {
            get {
                return ResourceManager.GetString("SpecialAction_Uncover", resourceCulture);
            }
        }
    }
}
