(define (problem castle)
	(:domain castle)
	(:objects 
        poison cupking cupprince cupprincess table chair - thing
		prince princess king maiden - character
		throneroom bedroomprincess guestroom diningroom kitchen prison corridor - place)
    (:init 
            (at prince throneroom)
            (at princess throneroom)
            (at king throneroom)
            (at maiden guestroom)
            (at poison bedroomprincess)
            (at cupking kitchen)
            (at cupprince kitchen)
            (at cupprincess kitchen)
            (dark guestroom)
            (light diningroom)
            (narrow corridor)
            (scary corridor)
            (sparse corridor)
            (small guestroom)
            (at table diningroom)
            (at chair diningroom)
            (at chair diningroom)
            (at chair diningroom)
            (at throne throneroom)
            (at chair throneroom)
            (around chair table)
    )
)