(define (plan castle)
	(:problem castle)
	(:steps
		(talkmultiple prince princess king throneroom1)
		(fallinlove princess prince throneroom1)
		(fallinlove prince princess throneroom1)
		(hides maiden guestroom1)
		(move prince throneroom1 guestroom1)
		(talk princess king throneroom1)
		(move princess throneroom1 corridor1)
		(move princess corridor1 guestroom1)
		(talk princess prince guestroom1)
		(move princess guestroom1 bedroomprincess1)
		(pickup princess poison bedroomprincess1)
		(move princess bedroomprincess1 guestroom1)
		(talk prince princess guestroom1)
		(give princess prince poison guestroom1)
		(move prince guestroom1 diningroom1)
		(move princess guestroom1 diningroom1)
		(move king throneroom1 diningroom1)
		(move maiden guestroom1 kitchen1)
		(hides maiden kitchen1)
		(talkmultiple prince princess king diningroom1)
		(move prince diningroom1 kitchen1)
		(poisons cupking poison kitchen1)
		(move prince kitchen1 diningroom1)
		(swaps maiden cupking cupprince kitchen1)
		(pickup maiden cupprince kitchen1)
		(move maiden kitchen1 diningroom1)
		(placeon maiden cupprince table diningroom1)
		(drink prince cupprince diningroom1)
		(dies prince diningroom1)
		(talk princess king diningroom1)
		(move princess diningroom1 prison1)
		(marry king maiden diningroom1)
	)
)