(define (plan red-cap)
	(:problem red-cap)
	(:steps
		(move redcap motherhouse wolfmeetingspot)
		(talk redcap wolf wolfmeetingspot)
		(move redcap wolfmeetingspot flowerpickuplocation)
		(pick-up redcap flowers flowerpickuplocation)
		(move wolf wolfmeetingspot outsidegrandmotherhouse)
		(move wolf outsidegrandmotherhouse insidegrandmotherhouse)
		(eat wolf grandmother insidegrandmotherhouse)
		(disguise wolf grandmother insidegrandmotherhouse)
		(move redcap flowerpickuplocation outsidegrandmotherhouse)
		(move redcap outsidegrandmotherhouse insidegrandmotherhouse)
		(talk redcap wolf insidegrandmotherhouse)
		(eat wolf redcap insidegrandmotherhouse)
		(move woodman woodmanshouse outsidegrandmotherhouse)
		(hears woodman wolf outsidegrandmotherhouse)
		(move woodman outsidegrandmotherhouse insidegrandmotherhouse)
		(cuts-open woodman wolf insidegrandmotherhouse)
		(skin woodman wolf insidegrandmotherhouse)
		(pick-up woodman wolfskin insidegrandmotherhouse)
		(move woodman insidegrandmotherhouse outsidegrandmotherhouse)
		(move woodman outsidegrandmotherhouse woodmanshouse)
		(eat redcap goodies insidegrandmotherhouse)
		(eat grandmother goodies insidegrandmotherhouse)
	)
)