//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantics.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericTables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericTables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantics.Data.GenericTables", typeof(GenericTables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_entity.
        /// </summary>
        public static string AbstractEntity {
            get {
                return ResourceManager.GetString("AbstractEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstraction.
        /// </summary>
        public static string Abstraction {
            get {
                return ResourceManager.GetString("Abstraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add_remove_requirements.
        /// </summary>
        public static string AddRemoveRequirements {
            get {
                return ResourceManager.GetString("AddRemoveRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chemical_substance.
        /// </summary>
        public static string ChemicalSubstance {
            get {
                return ResourceManager.GetString("ChemicalSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to combined_relationship.
        /// </summary>
        public static string CombinedRelationship {
            get {
                return ResourceManager.GetString("CombinedRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound.
        /// </summary>
        public static string Compound {
            get {
                return ResourceManager.GetString("Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_overridden_substance.
        /// </summary>
        public static string CompoundOverriddenSubstance {
            get {
                return ResourceManager.GetString("CompoundOverriddenSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_substance.
        /// </summary>
        public static string CompoundSubstance {
            get {
                return ResourceManager.GetString("CompoundSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context.
        /// </summary>
        public static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context_condition.
        /// </summary>
        public static string ContextCondition {
            get {
                return ResourceManager.GetString("ContextCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context_type.
        /// </summary>
        public static string ContextType {
            get {
                return ResourceManager.GetString("ContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_abstract_entity.
        /// </summary>
        public static string EntityAbstractEntity {
            get {
                return ResourceManager.GetString("EntityAbstractEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_attribute.
        /// </summary>
        public static string EntityAttribute {
            get {
                return ResourceManager.GetString("EntityAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_combined_relationship.
        /// </summary>
        public static string EntityCombinedRelationship {
            get {
                return ResourceManager.GetString("EntityCombinedRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_overridden_abstract_entity.
        /// </summary>
        public static string EntityOverriddenAbstractEntity {
            get {
                return ResourceManager.GetString("EntityOverriddenAbstractEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_overridden_attribute.
        /// </summary>
        public static string EntityOverriddenAttribute {
            get {
                return ResourceManager.GetString("EntityOverriddenAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_reference.
        /// </summary>
        public static string EntityReference {
            get {
                return ResourceManager.GetString("EntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_state_group.
        /// </summary>
        public static string EntityStateGroup {
            get {
                return ResourceManager.GetString("EntityStateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_variable.
        /// </summary>
        public static string EntityVariable {
            get {
                return ResourceManager.GetString("EntityVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_effect.
        /// </summary>
        public static string EventEffect {
            get {
                return ResourceManager.GetString("EventEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_reference.
        /// </summary>
        public static string EventReference {
            get {
                return ResourceManager.GetString("EventReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_requirements.
        /// </summary>
        public static string EventRequirements {
            get {
                return ResourceManager.GetString("EventRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_requirements_reference_requirements.
        /// </summary>
        public static string EventRequirementsReferenceRequirements {
            get {
                return ResourceManager.GetString("EventRequirementsReferenceRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_variable.
        /// </summary>
        public static string EventVariable {
            get {
                return ResourceManager.GetString("EventVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to family_condition.
        /// </summary>
        public static string FamilyCondition {
            get {
                return ResourceManager.GetString("FamilyCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feature.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter_effect.
        /// </summary>
        public static string FilterEffect {
            get {
                return ResourceManager.GetString("FilterEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter_type.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goal_change.
        /// </summary>
        public static string GoalChange {
            get {
                return ResourceManager.GetString("GoalChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group_.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group_entity.
        /// </summary>
        public static string GroupEntity {
            get {
                return ResourceManager.GetString("GroupEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter.
        /// </summary>
        public static string Matter {
            get {
                return ResourceManager.GetString("Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_element.
        /// </summary>
        public static string MatterElement {
            get {
                return ResourceManager.GetString("MatterElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_overridden_element.
        /// </summary>
        public static string MatterOverriddenElement {
            get {
                return ResourceManager.GetString("MatterOverriddenElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture.
        /// </summary>
        public static string Mixture {
            get {
                return ResourceManager.GetString("Mixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_mixture.
        /// </summary>
        public static string MixtureMixture {
            get {
                return ResourceManager.GetString("MixtureMixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_overridden_mixture.
        /// </summary>
        public static string MixtureOverriddenMixture {
            get {
                return ResourceManager.GetString("MixtureOverriddenMixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_overridden_substance.
        /// </summary>
        public static string MixtureOverriddenSubstance {
            get {
                return ResourceManager.GetString("MixtureOverriddenSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_substance.
        /// </summary>
        public static string MixtureSubstance {
            get {
                return ResourceManager.GetString("MixtureSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node.
        /// </summary>
        public static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node_parent.
        /// </summary>
        public static string NodeParent {
            get {
                return ResourceManager.GetString("NodeParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal_holder.
        /// </summary>
        public static string NormalHolder {
            get {
                return ResourceManager.GetString("NormalHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_entity.
        /// </summary>
        public static string PhysicalEntity {
            get {
                return ResourceManager.GetString("PhysicalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object.
        /// </summary>
        public static string PhysicalObject {
            get {
                return ResourceManager.GetString("PhysicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_overridden_space.
        /// </summary>
        public static string PhysicalObjectOverriddenSpace {
            get {
                return ResourceManager.GetString("PhysicalObjectOverriddenSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_space.
        /// </summary>
        public static string PhysicalObjectSpace {
            get {
                return ResourceManager.GetString("PhysicalObjectSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate.
        /// </summary>
        public static string Predicate {
            get {
                return ResourceManager.GetString("Predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate_reference.
        /// </summary>
        public static string PredicateReference {
            get {
                return ResourceManager.GetString("PredicateReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate_type.
        /// </summary>
        public static string PredicateType {
            get {
                return ResourceManager.GetString("PredicateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate_variable.
        /// </summary>
        public static string PredicateVariable {
            get {
                return ResourceManager.GetString("PredicateVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to procedure.
        /// </summary>
        public static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw_material.
        /// </summary>
        public static string RawMaterial {
            get {
                return ResourceManager.GetString("RawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_attribute.
        /// </summary>
        public static string RelationshipAttribute {
            get {
                return ResourceManager.GetString("RelationshipAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_instance.
        /// </summary>
        public static string RelationshipInstance {
            get {
                return ResourceManager.GetString("RelationshipInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_parameter.
        /// </summary>
        public static string RelationshipParameter {
            get {
                return ResourceManager.GetString("RelationshipParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_references.
        /// </summary>
        public static string RelationshipReferences {
            get {
                return ResourceManager.GetString("RelationshipReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_target.
        /// </summary>
        public static string RelationshipTarget {
            get {
                return ResourceManager.GetString("RelationshipTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_type.
        /// </summary>
        public static string RelationshipType {
            get {
                return ResourceManager.GetString("RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_type_attribute.
        /// </summary>
        public static string RelationshipTypeAttribute {
            get {
                return ResourceManager.GetString("RelationshipTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_type_parameter.
        /// </summary>
        public static string RelationshipTypeParameter {
            get {
                return ResourceManager.GetString("RelationshipTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_variable.
        /// </summary>
        public static string RelationshipVariable {
            get {
                return ResourceManager.GetString("RelationshipVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirements_condition.
        /// </summary>
        public static string RequirementsCondition {
            get {
                return ResourceManager.GetString("RequirementsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirements_context_type.
        /// </summary>
        public static string RequirementsContextType {
            get {
                return ResourceManager.GetString("RequirementsContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirements_spatial_requirement.
        /// </summary>
        public static string RequirementsSpatialRequirement {
            get {
                return ResourceManager.GetString("RequirementsSpatialRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scene_overridden_physical_object.
        /// </summary>
        public static string SceneOverriddenPhysicalObject {
            get {
                return ResourceManager.GetString("SceneOverriddenPhysicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scene_overridden_scene.
        /// </summary>
        public static string SceneOverriddenScene {
            get {
                return ResourceManager.GetString("SceneOverriddenScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scene_physical_object.
        /// </summary>
        public static string ScenePhysicalObject {
            get {
                return ResourceManager.GetString("ScenePhysicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scene_scene.
        /// </summary>
        public static string SceneScene {
            get {
                return ResourceManager.GetString("SceneScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semifinished_material.
        /// </summary>
        public static string SemifinishedMaterial {
            get {
                return ResourceManager.GetString("SemifinishedMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semifinished_material_raw_material.
        /// </summary>
        public static string SemifinishedMaterialRawMaterial {
            get {
                return ResourceManager.GetString("SemifinishedMaterialRawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_item.
        /// </summary>
        public static string SpaceItem {
            get {
                return ResourceManager.GetString("SpaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special_attributes.
        /// </summary>
        public static string SpecialAttributes {
            get {
                return ResourceManager.GetString("SpecialAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special_unit_categories.
        /// </summary>
        public static string SpecialUnitCategories {
            get {
                return ResourceManager.GetString("SpecialUnitCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state_group.
        /// </summary>
        public static string StateGroup {
            get {
                return ResourceManager.GetString("StateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state_group_state.
        /// </summary>
        public static string StateGroupState {
            get {
                return ResourceManager.GetString("StateGroupState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substance.
        /// </summary>
        public static string Substance {
            get {
                return ResourceManager.GetString("Substance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object.
        /// </summary>
        public static string TangibleObject {
            get {
                return ResourceManager.GetString("TangibleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_connection_item.
        /// </summary>
        public static string TangibleObjectConnectionItem {
            get {
                return ResourceManager.GetString("TangibleObjectConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_cover.
        /// </summary>
        public static string TangibleObjectCover {
            get {
                return ResourceManager.GetString("TangibleObjectCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_layer.
        /// </summary>
        public static string TangibleObjectLayer {
            get {
                return ResourceManager.GetString("TangibleObjectLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_matter.
        /// </summary>
        public static string TangibleObjectMatter {
            get {
                return ResourceManager.GetString("TangibleObjectMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_overridden_connection_item.
        /// </summary>
        public static string TangibleObjectOverriddenConnectionItem {
            get {
                return ResourceManager.GetString("TangibleObjectOverriddenConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_overridden_cover.
        /// </summary>
        public static string TangibleObjectOverriddenCover {
            get {
                return ResourceManager.GetString("TangibleObjectOverriddenCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_overridden_layer.
        /// </summary>
        public static string TangibleObjectOverriddenLayer {
            get {
                return ResourceManager.GetString("TangibleObjectOverriddenLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_overridden_matter.
        /// </summary>
        public static string TangibleObjectOverriddenMatter {
            get {
                return ResourceManager.GetString("TangibleObjectOverriddenMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_overridden_part.
        /// </summary>
        public static string TangibleObjectOverriddenPart {
            get {
                return ResourceManager.GetString("TangibleObjectOverriddenPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_part.
        /// </summary>
        public static string TangibleObjectPart {
            get {
                return ResourceManager.GetString("TangibleObjectPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit_category.
        /// </summary>
        public static string UnitCategory {
            get {
                return ResourceManager.GetString("UnitCategory", resourceCulture);
            }
        }
    }
}
