//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantics.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValueTables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValueTables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantics.Data.ValueTables", typeof(ValueTables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_entity_change.
        /// </summary>
        public static string AbstractEntityChange {
            get {
                return ResourceManager.GetString("AbstractEntityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_entity_condition.
        /// </summary>
        public static string AbstractEntityCondition {
            get {
                return ResourceManager.GetString("AbstractEntityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_entity_valued.
        /// </summary>
        public static string AbstractEntityValued {
            get {
                return ResourceManager.GetString("AbstractEntityValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstraction_change.
        /// </summary>
        public static string AbstractionChange {
            get {
                return ResourceManager.GetString("AbstractionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstraction_condition.
        /// </summary>
        public static string AbstractionCondition {
            get {
                return ResourceManager.GetString("AbstractionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstraction_valued.
        /// </summary>
        public static string AbstractionValued {
            get {
                return ResourceManager.GetString("AbstractionValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute_change.
        /// </summary>
        public static string AttributeChange {
            get {
                return ResourceManager.GetString("AttributeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute_condition.
        /// </summary>
        public static string AttributeCondition {
            get {
                return ResourceManager.GetString("AttributeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute_valued.
        /// </summary>
        public static string AttributeValued {
            get {
                return ResourceManager.GetString("AttributeValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool_value.
        /// </summary>
        public static string BoolValue {
            get {
                return ResourceManager.GetString("BoolValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool_value_change.
        /// </summary>
        public static string BoolValueChange {
            get {
                return ResourceManager.GetString("BoolValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool_value_condition.
        /// </summary>
        public static string BoolValueCondition {
            get {
                return ResourceManager.GetString("BoolValueCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool_variable.
        /// </summary>
        public static string BoolVariable {
            get {
                return ResourceManager.GetString("BoolVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chance.
        /// </summary>
        public static string Chance {
            get {
                return ResourceManager.GetString("Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_change.
        /// </summary>
        public static string CompoundChange {
            get {
                return ResourceManager.GetString("CompoundChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_change_substance_change.
        /// </summary>
        public static string CompoundChangeSubstanceChange {
            get {
                return ResourceManager.GetString("CompoundChangeSubstanceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_change_substance_to_add.
        /// </summary>
        public static string CompoundChangeSubstanceToAdd {
            get {
                return ResourceManager.GetString("CompoundChangeSubstanceToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_change_substance_to_remove.
        /// </summary>
        public static string CompoundChangeSubstanceToRemove {
            get {
                return ResourceManager.GetString("CompoundChangeSubstanceToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_condition.
        /// </summary>
        public static string CompoundCondition {
            get {
                return ResourceManager.GetString("CompoundCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_condition_substance_condition.
        /// </summary>
        public static string CompoundConditionSubstanceCondition {
            get {
                return ResourceManager.GetString("CompoundConditionSubstanceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compound_valued.
        /// </summary>
        public static string CompoundValued {
            get {
                return ResourceManager.GetString("CompoundValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection_item.
        /// </summary>
        public static string ConnectionItem {
            get {
                return ResourceManager.GetString("ConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection_item_change.
        /// </summary>
        public static string ConnectionItemChange {
            get {
                return ResourceManager.GetString("ConnectionItemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection_item_condition.
        /// </summary>
        public static string ConnectionItemCondition {
            get {
                return ResourceManager.GetString("ConnectionItemCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection_reference.
        /// </summary>
        public static string ConnectionReference {
            get {
                return ResourceManager.GetString("ConnectionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cover.
        /// </summary>
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cover_change.
        /// </summary>
        public static string CoverChange {
            get {
                return ResourceManager.GetString("CoverChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cover_condition.
        /// </summary>
        public static string CoverCondition {
            get {
                return ResourceManager.GetString("CoverCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cover_reference.
        /// </summary>
        public static string CoverReference {
            get {
                return ResourceManager.GetString("CoverReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletion.
        /// </summary>
        public static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to effect.
        /// </summary>
        public static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element_change.
        /// </summary>
        public static string ElementChange {
            get {
                return ResourceManager.GetString("ElementChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element_condition.
        /// </summary>
        public static string ElementCondition {
            get {
                return ResourceManager.GetString("ElementCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element_valued.
        /// </summary>
        public static string ElementValued {
            get {
                return ResourceManager.GetString("ElementValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change.
        /// </summary>
        public static string EntityChange {
            get {
                return ResourceManager.GetString("EntityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_abstract_entity_change.
        /// </summary>
        public static string EntityChangeAbstractEntityChange {
            get {
                return ResourceManager.GetString("EntityChangeAbstractEntityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_abstract_entity_to_add.
        /// </summary>
        public static string EntityChangeAbstractEntityToAdd {
            get {
                return ResourceManager.GetString("EntityChangeAbstractEntityToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_abstract_entity_to_remove.
        /// </summary>
        public static string EntityChangeAbstractEntityToRemove {
            get {
                return ResourceManager.GetString("EntityChangeAbstractEntityToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_attribute_change.
        /// </summary>
        public static string EntityChangeAttributeChange {
            get {
                return ResourceManager.GetString("EntityChangeAttributeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_attribute_to_add.
        /// </summary>
        public static string EntityChangeAttributeToAdd {
            get {
                return ResourceManager.GetString("EntityChangeAttributeToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_attribute_to_remove.
        /// </summary>
        public static string EntityChangeAttributeToRemove {
            get {
                return ResourceManager.GetString("EntityChangeAttributeToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_relationship_change.
        /// </summary>
        public static string EntityChangeRelationshipChange {
            get {
                return ResourceManager.GetString("EntityChangeRelationshipChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_change_state_group_change.
        /// </summary>
        public static string EntityChangeStateGroupChange {
            get {
                return ResourceManager.GetString("EntityChangeStateGroupChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_condition.
        /// </summary>
        public static string EntityCondition {
            get {
                return ResourceManager.GetString("EntityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_condition_abstract_entity_condition.
        /// </summary>
        public static string EntityConditionAbstractEntityCondition {
            get {
                return ResourceManager.GetString("EntityConditionAbstractEntityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_condition_action.
        /// </summary>
        public static string EntityConditionAction {
            get {
                return ResourceManager.GetString("EntityConditionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_condition_attribute_condition.
        /// </summary>
        public static string EntityConditionAttributeCondition {
            get {
                return ResourceManager.GetString("EntityConditionAttributeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_condition_relationship_condition.
        /// </summary>
        public static string EntityConditionRelationshipCondition {
            get {
                return ResourceManager.GetString("EntityConditionRelationshipCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_condition_state_group_condition.
        /// </summary>
        public static string EntityConditionStateGroupCondition {
            get {
                return ResourceManager.GetString("EntityConditionStateGroupCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_creation.
        /// </summary>
        public static string EntityCreation {
            get {
                return ResourceManager.GetString("EntityCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity_valued.
        /// </summary>
        public static string EntityValued {
            get {
                return ResourceManager.GetString("EntityValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equation.
        /// </summary>
        public static string Equation {
            get {
                return ResourceManager.GetString("Equation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feature_change.
        /// </summary>
        public static string FeatureChange {
            get {
                return ResourceManager.GetString("FeatureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feature_condition.
        /// </summary>
        public static string FeatureCondition {
            get {
                return ResourceManager.GetString("FeatureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feature_valued.
        /// </summary>
        public static string FeatureValued {
            get {
                return ResourceManager.GetString("FeatureValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter_application.
        /// </summary>
        public static string FilterApplication {
            get {
                return ResourceManager.GetString("FilterApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item_reference.
        /// </summary>
        public static string ItemReference {
            get {
                return ResourceManager.GetString("ItemReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer.
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer_change.
        /// </summary>
        public static string LayerChange {
            get {
                return ResourceManager.GetString("LayerChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer_condition.
        /// </summary>
        public static string LayerCondition {
            get {
                return ResourceManager.GetString("LayerCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer_reference.
        /// </summary>
        public static string LayerReference {
            get {
                return ResourceManager.GetString("LayerReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to material_change.
        /// </summary>
        public static string MaterialChange {
            get {
                return ResourceManager.GetString("MaterialChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to material_condition.
        /// </summary>
        public static string MaterialCondition {
            get {
                return ResourceManager.GetString("MaterialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to material_valued.
        /// </summary>
        public static string MaterialValued {
            get {
                return ResourceManager.GetString("MaterialValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_change.
        /// </summary>
        public static string MatterChange {
            get {
                return ResourceManager.GetString("MatterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_change_element_change.
        /// </summary>
        public static string MatterChangeElementChange {
            get {
                return ResourceManager.GetString("MatterChangeElementChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_change_element_to_add.
        /// </summary>
        public static string MatterChangeElementToAdd {
            get {
                return ResourceManager.GetString("MatterChangeElementToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_change_element_to_remove.
        /// </summary>
        public static string MatterChangeElementToRemove {
            get {
                return ResourceManager.GetString("MatterChangeElementToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_condition.
        /// </summary>
        public static string MatterCondition {
            get {
                return ResourceManager.GetString("MatterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_condition_element_condition.
        /// </summary>
        public static string MatterConditionElementCondition {
            get {
                return ResourceManager.GetString("MatterConditionElementCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_reference.
        /// </summary>
        public static string MatterReference {
            get {
                return ResourceManager.GetString("MatterReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_valued.
        /// </summary>
        public static string MatterValued {
            get {
                return ResourceManager.GetString("MatterValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_change.
        /// </summary>
        public static string MixtureChange {
            get {
                return ResourceManager.GetString("MixtureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_change_mixture_to_add.
        /// </summary>
        public static string MixtureChangeMixtureToAdd {
            get {
                return ResourceManager.GetString("MixtureChangeMixtureToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_change_substance_change.
        /// </summary>
        public static string MixtureChangeSubstanceChange {
            get {
                return ResourceManager.GetString("MixtureChangeSubstanceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_change_substance_to_add.
        /// </summary>
        public static string MixtureChangeSubstanceToAdd {
            get {
                return ResourceManager.GetString("MixtureChangeSubstanceToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_change_substance_to_remove.
        /// </summary>
        public static string MixtureChangeSubstanceToRemove {
            get {
                return ResourceManager.GetString("MixtureChangeSubstanceToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_condition.
        /// </summary>
        public static string MixtureCondition {
            get {
                return ResourceManager.GetString("MixtureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_condition_substance_condition.
        /// </summary>
        public static string MixtureConditionSubstanceCondition {
            get {
                return ResourceManager.GetString("MixtureConditionSubstanceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixture_valued.
        /// </summary>
        public static string MixtureValued {
            get {
                return ResourceManager.GetString("MixtureValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node_change.
        /// </summary>
        public static string NodeChange {
            get {
                return ResourceManager.GetString("NodeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node_condition.
        /// </summary>
        public static string NodeCondition {
            get {
                return ResourceManager.GetString("NodeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node_valued.
        /// </summary>
        public static string NodeValued {
            get {
                return ResourceManager.GetString("NodeValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numerical_value.
        /// </summary>
        public static string NumericalValue {
            get {
                return ResourceManager.GetString("NumericalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numerical_value_change.
        /// </summary>
        public static string NumericalValueChange {
            get {
                return ResourceManager.GetString("NumericalValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numerical_value_condition.
        /// </summary>
        public static string NumericalValueCondition {
            get {
                return ResourceManager.GetString("NumericalValueCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numerical_value_range.
        /// </summary>
        public static string NumericalValueRange {
            get {
                return ResourceManager.GetString("NumericalValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numerical_variable.
        /// </summary>
        public static string NumericalVariable {
            get {
                return ResourceManager.GetString("NumericalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owner_reference.
        /// </summary>
        public static string OwnerReference {
            get {
                return ResourceManager.GetString("OwnerReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter_valued.
        /// </summary>
        public static string ParameterValued {
            get {
                return ResourceManager.GetString("ParameterValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part_change.
        /// </summary>
        public static string PartChange {
            get {
                return ResourceManager.GetString("PartChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part_condition.
        /// </summary>
        public static string PartCondition {
            get {
                return ResourceManager.GetString("PartCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part_reference.
        /// </summary>
        public static string PartReference {
            get {
                return ResourceManager.GetString("PartReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_entity_change.
        /// </summary>
        public static string PhysicalEntityChange {
            get {
                return ResourceManager.GetString("PhysicalEntityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_entity_condition.
        /// </summary>
        public static string PhysicalEntityCondition {
            get {
                return ResourceManager.GetString("PhysicalEntityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_entity_valued.
        /// </summary>
        public static string PhysicalEntityValued {
            get {
                return ResourceManager.GetString("PhysicalEntityValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_change.
        /// </summary>
        public static string PhysicalObjectChange {
            get {
                return ResourceManager.GetString("PhysicalObjectChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_change_space_change.
        /// </summary>
        public static string PhysicalObjectChangeSpaceChange {
            get {
                return ResourceManager.GetString("PhysicalObjectChangeSpaceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_change_space_to_add.
        /// </summary>
        public static string PhysicalObjectChangeSpaceToAdd {
            get {
                return ResourceManager.GetString("PhysicalObjectChangeSpaceToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_change_space_to_remove.
        /// </summary>
        public static string PhysicalObjectChangeSpaceToRemove {
            get {
                return ResourceManager.GetString("PhysicalObjectChangeSpaceToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_condition.
        /// </summary>
        public static string PhysicalObjectCondition {
            get {
                return ResourceManager.GetString("PhysicalObjectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_condition_space_condition.
        /// </summary>
        public static string PhysicalObjectConditionSpaceCondition {
            get {
                return ResourceManager.GetString("PhysicalObjectConditionSpaceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical_object_valued.
        /// </summary>
        public static string PhysicalObjectValued {
            get {
                return ResourceManager.GetString("PhysicalObjectValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random_variable.
        /// </summary>
        public static string RandomVariable {
            get {
                return ResourceManager.GetString("RandomVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range_specific_target.
        /// </summary>
        public static string RangeSpecificTarget {
            get {
                return ResourceManager.GetString("RangeSpecificTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw_material_change.
        /// </summary>
        public static string RawMaterialChange {
            get {
                return ResourceManager.GetString("RawMaterialChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw_material_condition.
        /// </summary>
        public static string RawMaterialCondition {
            get {
                return ResourceManager.GetString("RawMaterialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw_material_valued.
        /// </summary>
        public static string RawMaterialValued {
            get {
                return ResourceManager.GetString("RawMaterialValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reaction.
        /// </summary>
        public static string Reaction {
            get {
                return ResourceManager.GetString("Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_change.
        /// </summary>
        public static string RelationshipChange {
            get {
                return ResourceManager.GetString("RelationshipChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_change_attribute_change.
        /// </summary>
        public static string RelationshipChangeAttributeChange {
            get {
                return ResourceManager.GetString("RelationshipChangeAttributeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_condition.
        /// </summary>
        public static string RelationshipCondition {
            get {
                return ResourceManager.GetString("RelationshipCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_condition_attribute_condition.
        /// </summary>
        public static string RelationshipConditionAttributeCondition {
            get {
                return ResourceManager.GetString("RelationshipConditionAttributeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_establishment.
        /// </summary>
        public static string RelationshipEstablishment {
            get {
                return ResourceManager.GetString("RelationshipEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationship_reference.
        /// </summary>
        public static string RelationshipReference {
            get {
                return ResourceManager.GetString("RelationshipReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scene_valued.
        /// </summary>
        public static string SceneValued {
            get {
                return ResourceManager.GetString("SceneValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semifinished_material_change.
        /// </summary>
        public static string SemifinishedMaterialChange {
            get {
                return ResourceManager.GetString("SemifinishedMaterialChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semifinished_material_condition.
        /// </summary>
        public static string SemifinishedMaterialCondition {
            get {
                return ResourceManager.GetString("SemifinishedMaterialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semifinished_material_condition_raw_material_condition.
        /// </summary>
        public static string SemifinishedMaterialConditionRawMaterialCondition {
            get {
                return ResourceManager.GetString("SemifinishedMaterialConditionRawMaterialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semifinished_material_valued.
        /// </summary>
        public static string SemifinishedMaterialValued {
            get {
                return ResourceManager.GetString("SemifinishedMaterialValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set_reference.
        /// </summary>
        public static string SetReference {
            get {
                return ResourceManager.GetString("SetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_change.
        /// </summary>
        public static string SpaceChange {
            get {
                return ResourceManager.GetString("SpaceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_change_item.
        /// </summary>
        public static string SpaceChangeItem {
            get {
                return ResourceManager.GetString("SpaceChangeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_change_item_to_add.
        /// </summary>
        public static string SpaceChangeItemToAdd {
            get {
                return ResourceManager.GetString("SpaceChangeItemToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_change_item_to_remove.
        /// </summary>
        public static string SpaceChangeItemToRemove {
            get {
                return ResourceManager.GetString("SpaceChangeItemToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_change_tangible_matter.
        /// </summary>
        public static string SpaceChangeTangibleMatter {
            get {
                return ResourceManager.GetString("SpaceChangeTangibleMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_change_tangible_matter_to_add.
        /// </summary>
        public static string SpaceChangeTangibleMatterToAdd {
            get {
                return ResourceManager.GetString("SpaceChangeTangibleMatterToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_change_tangible_matter_to_remove.
        /// </summary>
        public static string SpaceChangeTangibleMatterToRemove {
            get {
                return ResourceManager.GetString("SpaceChangeTangibleMatterToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_condition.
        /// </summary>
        public static string SpaceCondition {
            get {
                return ResourceManager.GetString("SpaceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_condition_item.
        /// </summary>
        public static string SpaceConditionItem {
            get {
                return ResourceManager.GetString("SpaceConditionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_condition_tangible_matter.
        /// </summary>
        public static string SpaceConditionTangibleMatter {
            get {
                return ResourceManager.GetString("SpaceConditionTangibleMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_reference.
        /// </summary>
        public static string SpaceReference {
            get {
                return ResourceManager.GetString("SpaceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_valued.
        /// </summary>
        public static string SpaceValued {
            get {
                return ResourceManager.GetString("SpaceValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_valued_item.
        /// </summary>
        public static string SpaceValuedItem {
            get {
                return ResourceManager.GetString("SpaceValuedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space_valued_tangible_matter.
        /// </summary>
        public static string SpaceValuedTangibleMatter {
            get {
                return ResourceManager.GetString("SpaceValuedTangibleMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spatial_reference.
        /// </summary>
        public static string SpatialReference {
            get {
                return ResourceManager.GetString("SpatialReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spatial_requirement.
        /// </summary>
        public static string SpatialRequirement {
            get {
                return ResourceManager.GetString("SpatialRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state_group_change.
        /// </summary>
        public static string StateGroupChange {
            get {
                return ResourceManager.GetString("StateGroupChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state_group_condition.
        /// </summary>
        public static string StateGroupCondition {
            get {
                return ResourceManager.GetString("StateGroupCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state_group_condition_state.
        /// </summary>
        public static string StateGroupConditionState {
            get {
                return ResourceManager.GetString("StateGroupConditionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string_value.
        /// </summary>
        public static string StringValue {
            get {
                return ResourceManager.GetString("StringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string_value_change.
        /// </summary>
        public static string StringValueChange {
            get {
                return ResourceManager.GetString("StringValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string_value_condition.
        /// </summary>
        public static string StringValueCondition {
            get {
                return ResourceManager.GetString("StringValueCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string_variable.
        /// </summary>
        public static string StringVariable {
            get {
                return ResourceManager.GetString("StringVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substance_change.
        /// </summary>
        public static string SubstanceChange {
            get {
                return ResourceManager.GetString("SubstanceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substance_condition.
        /// </summary>
        public static string SubstanceCondition {
            get {
                return ResourceManager.GetString("SubstanceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substance_valued.
        /// </summary>
        public static string SubstanceValued {
            get {
                return ResourceManager.GetString("SubstanceValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change.
        /// </summary>
        public static string TangibleObjectChange {
            get {
                return ResourceManager.GetString("TangibleObjectChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_connection_item_change.
        /// </summary>
        public static string TangibleObjectChangeConnectionChange {
            get {
                return ResourceManager.GetString("TangibleObjectChangeConnectionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_connection_item_to_add.
        /// </summary>
        public static string TangibleObjectChangeConnectionToAdd {
            get {
                return ResourceManager.GetString("TangibleObjectChangeConnectionToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_connection_item_to_remove.
        /// </summary>
        public static string TangibleObjectChangeConnectionToRemove {
            get {
                return ResourceManager.GetString("TangibleObjectChangeConnectionToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_cover_change.
        /// </summary>
        public static string TangibleObjectChangeCoverChange {
            get {
                return ResourceManager.GetString("TangibleObjectChangeCoverChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_cover_to_add.
        /// </summary>
        public static string TangibleObjectChangeCoverToAdd {
            get {
                return ResourceManager.GetString("TangibleObjectChangeCoverToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_cover_to_remove.
        /// </summary>
        public static string TangibleObjectChangeCoverToRemove {
            get {
                return ResourceManager.GetString("TangibleObjectChangeCoverToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_layer_change.
        /// </summary>
        public static string TangibleObjectChangeLayerChange {
            get {
                return ResourceManager.GetString("TangibleObjectChangeLayerChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_layer_to_add.
        /// </summary>
        public static string TangibleObjectChangeLayerToAdd {
            get {
                return ResourceManager.GetString("TangibleObjectChangeLayerToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_layer_to_remove.
        /// </summary>
        public static string TangibleObjectChangeLayerToRemove {
            get {
                return ResourceManager.GetString("TangibleObjectChangeLayerToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_matter_change.
        /// </summary>
        public static string TangibleObjectChangeMatterChange {
            get {
                return ResourceManager.GetString("TangibleObjectChangeMatterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_matter_to_add.
        /// </summary>
        public static string TangibleObjectChangeMatterToAdd {
            get {
                return ResourceManager.GetString("TangibleObjectChangeMatterToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_matter_to_remove.
        /// </summary>
        public static string TangibleObjectChangeMatterToRemove {
            get {
                return ResourceManager.GetString("TangibleObjectChangeMatterToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_part_change.
        /// </summary>
        public static string TangibleObjectChangePartChange {
            get {
                return ResourceManager.GetString("TangibleObjectChangePartChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_part_to_add.
        /// </summary>
        public static string TangibleObjectChangePartToAdd {
            get {
                return ResourceManager.GetString("TangibleObjectChangePartToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_change_part_to_remove.
        /// </summary>
        public static string TangibleObjectChangePartToRemove {
            get {
                return ResourceManager.GetString("TangibleObjectChangePartToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_condition.
        /// </summary>
        public static string TangibleObjectCondition {
            get {
                return ResourceManager.GetString("TangibleObjectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_condition_connection_item.
        /// </summary>
        public static string TangibleObjectConditionConnectionItem {
            get {
                return ResourceManager.GetString("TangibleObjectConditionConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_condition_cover_condition.
        /// </summary>
        public static string TangibleObjectConditionCoverCondition {
            get {
                return ResourceManager.GetString("TangibleObjectConditionCoverCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_condition_layer_condition.
        /// </summary>
        public static string TangibleObjectConditionLayerCondition {
            get {
                return ResourceManager.GetString("TangibleObjectConditionLayerCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_condition_matter_condition.
        /// </summary>
        public static string TangibleObjectConditionMatterCondition {
            get {
                return ResourceManager.GetString("TangibleObjectConditionMatterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_condition_part_condition.
        /// </summary>
        public static string TangibleObjectConditionPartCondition {
            get {
                return ResourceManager.GetString("TangibleObjectConditionPartCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object_valued.
        /// </summary>
        public static string TangibleObjectValued {
            get {
                return ResourceManager.GetString("TangibleObjectValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term_value.
        /// </summary>
        public static string TermValue {
            get {
                return ResourceManager.GetString("TermValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term_variable.
        /// </summary>
        public static string TermVariable {
            get {
                return ResourceManager.GetString("TermVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer_item.
        /// </summary>
        public static string TransferItem {
            get {
                return ResourceManager.GetString("TransferItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transformation.
        /// </summary>
        public static string Transformation {
            get {
                return ResourceManager.GetString("Transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transformation_entity.
        /// </summary>
        public static string TransformationEntity {
            get {
                return ResourceManager.GetString("TransformationEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value_change.
        /// </summary>
        public static string ValueChange {
            get {
                return ResourceManager.GetString("ValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value_condition.
        /// </summary>
        public static string ValueCondition {
            get {
                return ResourceManager.GetString("ValueCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector_value.
        /// </summary>
        public static string VectorValue {
            get {
                return ResourceManager.GetString("VectorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector_value_change.
        /// </summary>
        public static string VectorValueChange {
            get {
                return ResourceManager.GetString("VectorValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector_value_condition.
        /// </summary>
        public static string VectorValueCondition {
            get {
                return ResourceManager.GetString("VectorValueCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector_variable.
        /// </summary>
        public static string VectorVariable {
            get {
                return ResourceManager.GetString("VectorVariable", resourceCulture);
            }
        }
    }
}
