//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSemantics.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameTables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameTables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSemantics.Data.GameTables", typeof(GameTables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_game_node.
        /// </summary>
        public static string AbstractGameNode {
            get {
                return ResourceManager.GetString("AbstractGameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_game_node_dynamic_content.
        /// </summary>
        public static string AbstractGameNodeDynamicContent {
            get {
                return ResourceManager.GetString("AbstractGameNodeDynamicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_game_node_event_content.
        /// </summary>
        public static string AbstractGameNodeEventContent {
            get {
                return ResourceManager.GetString("AbstractGameNodeEventContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_game_node_event_extension.
        /// </summary>
        public static string AbstractGameNodeEventExtension {
            get {
                return ResourceManager.GetString("AbstractGameNodeEventExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_game_node_views_per_context_type.
        /// </summary>
        public static string AbstractGameNodeViewsPerContextType {
            get {
                return ResourceManager.GetString("AbstractGameNodeViewsPerContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinematic.
        /// </summary>
        public static string Cinematic {
            get {
                return ResourceManager.GetString("Cinematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_per_view.
        /// </summary>
        public static string ContentPerView {
            get {
                return ResourceManager.GetString("ContentPerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_per_view_content_valued.
        /// </summary>
        public static string ContentPerViewContentValued {
            get {
                return ResourceManager.GetString("ContentPerViewContentValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_predicate_type.
        /// </summary>
        public static string ContentPredicateType {
            get {
                return ResourceManager.GetString("ContentPredicateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic_content.
        /// </summary>
        public static string DynamicContent {
            get {
                return ResourceManager.GetString("DynamicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_content.
        /// </summary>
        public static string EventContent {
            get {
                return ResourceManager.GetString("EventContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_extension.
        /// </summary>
        public static string EventExtension {
            get {
                return ResourceManager.GetString("EventExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_extension_actor_content_condition.
        /// </summary>
        public static string EventExtensionActorContentCondition {
            get {
                return ResourceManager.GetString("EventExtensionActorContentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_extension_artifact_content_condition.
        /// </summary>
        public static string EventExtensionArtifactContentCondition {
            get {
                return ResourceManager.GetString("EventExtensionArtifactContentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_extension_content_change.
        /// </summary>
        public static string EventExtensionContentChange {
            get {
                return ResourceManager.GetString("EventExtensionContentChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_extension_target_content_condition.
        /// </summary>
        public static string EventExtensionTargetContentCondition {
            get {
                return ResourceManager.GetString("EventExtensionTargetContentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_filter.
        /// </summary>
        public static string GameFilter {
            get {
                return ResourceManager.GetString("GameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_material.
        /// </summary>
        public static string GameMaterial {
            get {
                return ResourceManager.GetString("GameMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_node.
        /// </summary>
        public static string GameNode {
            get {
                return ResourceManager.GetString("GameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_object.
        /// </summary>
        public static string GameObject {
            get {
                return ResourceManager.GetString("GameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_object_cover_game_objects.
        /// </summary>
        public static string GameObjectCoverGameObjects {
            get {
                return ResourceManager.GetString("GameObjectCoverGameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_object_layer_game_nodes.
        /// </summary>
        public static string GameObjectLayerGameNodes {
            get {
                return ResourceManager.GetString("GameObjectLayerGameNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_object_matter.
        /// </summary>
        public static string GameObjectMatter {
            get {
                return ResourceManager.GetString("GameObjectMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_object_part_game_objects.
        /// </summary>
        public static string GameObjectPartGameObjects {
            get {
                return ResourceManager.GetString("GameObjectPartGameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model_argument.
        /// </summary>
        public static string ModelArgument {
            get {
                return ResourceManager.GetString("ModelArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_emitter.
        /// </summary>
        public static string ParticleEmitter {
            get {
                return ResourceManager.GetString("ParticleEmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties.
        /// </summary>
        public static string ParticleProperties {
            get {
                return ResourceManager.GetString("ParticleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script.
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprite.
        /// </summary>
        public static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static_content.
        /// </summary>
        public static string StaticContent {
            get {
                return ResourceManager.GetString("StaticContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view_.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to views_per_context_type.
        /// </summary>
        public static string ViewsPerContextType {
            get {
                return ResourceManager.GetString("ViewsPerContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to views_per_context_type_content_per_view.
        /// </summary>
        public static string ViewsPerContextTypeContentPerView {
            get {
                return ResourceManager.GetString("ViewsPerContextTypeContentPerView", resourceCulture);
            }
        }
    }
}
