//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSemantics.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameValueTables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameValueTables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSemantics.Data.GameValueTables", typeof(GameValueTables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation_change.
        /// </summary>
        public static string AnimationChange {
            get {
                return ResourceManager.GetString("AnimationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation_condition.
        /// </summary>
        public static string AnimationCondition {
            get {
                return ResourceManager.GetString("AnimationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation_valued.
        /// </summary>
        public static string AnimationValued {
            get {
                return ResourceManager.GetString("AnimationValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio_change.
        /// </summary>
        public static string AudioChange {
            get {
                return ResourceManager.GetString("AudioChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio_condition.
        /// </summary>
        public static string AudioCondition {
            get {
                return ResourceManager.GetString("AudioCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio_valued.
        /// </summary>
        public static string AudioValued {
            get {
                return ResourceManager.GetString("AudioValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinematic_change.
        /// </summary>
        public static string CinematicChange {
            get {
                return ResourceManager.GetString("CinematicChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinematic_condition.
        /// </summary>
        public static string CinematicCondition {
            get {
                return ResourceManager.GetString("CinematicCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinematic_valued.
        /// </summary>
        public static string CinematicValued {
            get {
                return ResourceManager.GetString("CinematicValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_change.
        /// </summary>
        public static string ContentChange {
            get {
                return ResourceManager.GetString("ContentChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_change_predicate_type_to_add.
        /// </summary>
        public static string ContentChangePredicateTypeToAdd {
            get {
                return ResourceManager.GetString("ContentChangePredicateTypeToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_change_predicate_type_to_remove.
        /// </summary>
        public static string ContentChangePredicateTypeToRemove {
            get {
                return ResourceManager.GetString("ContentChangePredicateTypeToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_condition.
        /// </summary>
        public static string ContentCondition {
            get {
                return ResourceManager.GetString("ContentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_condition_predicate_type.
        /// </summary>
        public static string ContentConditionPredicateType {
            get {
                return ResourceManager.GetString("ContentConditionPredicateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_valued.
        /// </summary>
        public static string ContentValued {
            get {
                return ResourceManager.GetString("ContentValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic_content_change.
        /// </summary>
        public static string DynamicContentChange {
            get {
                return ResourceManager.GetString("DynamicContentChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic_content_condition.
        /// </summary>
        public static string DynamicContentCondition {
            get {
                return ResourceManager.GetString("DynamicContentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic_content_valued.
        /// </summary>
        public static string DynamicContentValued {
            get {
                return ResourceManager.GetString("DynamicContentValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_filter_change.
        /// </summary>
        public static string GameFilterChange {
            get {
                return ResourceManager.GetString("GameFilterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_filter_condition.
        /// </summary>
        public static string GameFilterCondition {
            get {
                return ResourceManager.GetString("GameFilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_filter_valued.
        /// </summary>
        public static string GameFilterValued {
            get {
                return ResourceManager.GetString("GameFilterValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_material_change.
        /// </summary>
        public static string GameMaterialChange {
            get {
                return ResourceManager.GetString("GameMaterialChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_material_condition.
        /// </summary>
        public static string GameMaterialCondition {
            get {
                return ResourceManager.GetString("GameMaterialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_material_valued.
        /// </summary>
        public static string GameMaterialValued {
            get {
                return ResourceManager.GetString("GameMaterialValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_change.
        /// </summary>
        public static string IconChange {
            get {
                return ResourceManager.GetString("IconChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_condition.
        /// </summary>
        public static string IconCondition {
            get {
                return ResourceManager.GetString("IconCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_valued.
        /// </summary>
        public static string IconValued {
            get {
                return ResourceManager.GetString("IconValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model_change.
        /// </summary>
        public static string ModelChange {
            get {
                return ResourceManager.GetString("ModelChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model_condition.
        /// </summary>
        public static string ModelCondition {
            get {
                return ResourceManager.GetString("ModelCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model_valued.
        /// </summary>
        public static string ModelValued {
            get {
                return ResourceManager.GetString("ModelValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_emitter_change.
        /// </summary>
        public static string ParticleEmitterChange {
            get {
                return ResourceManager.GetString("ParticleEmitterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_emitter_condition.
        /// </summary>
        public static string ParticleEmitterCondition {
            get {
                return ResourceManager.GetString("ParticleEmitterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_emitter_valued.
        /// </summary>
        public static string ParticleEmitterValued {
            get {
                return ResourceManager.GetString("ParticleEmitterValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties_change.
        /// </summary>
        public static string ParticlePropertiesChange {
            get {
                return ResourceManager.GetString("ParticlePropertiesChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties_condition.
        /// </summary>
        public static string ParticlePropertiesCondition {
            get {
                return ResourceManager.GetString("ParticlePropertiesCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties_valued.
        /// </summary>
        public static string ParticlePropertiesValued {
            get {
                return ResourceManager.GetString("ParticlePropertiesValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script_change.
        /// </summary>
        public static string ScriptChange {
            get {
                return ResourceManager.GetString("ScriptChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script_condition.
        /// </summary>
        public static string ScriptCondition {
            get {
                return ResourceManager.GetString("ScriptCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script_valued.
        /// </summary>
        public static string ScriptValued {
            get {
                return ResourceManager.GetString("ScriptValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprite_change.
        /// </summary>
        public static string SpriteChange {
            get {
                return ResourceManager.GetString("SpriteChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprite_condition.
        /// </summary>
        public static string SpriteCondition {
            get {
                return ResourceManager.GetString("SpriteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprite_valued.
        /// </summary>
        public static string SpriteValued {
            get {
                return ResourceManager.GetString("SpriteValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static_content_change.
        /// </summary>
        public static string StaticContentChange {
            get {
                return ResourceManager.GetString("StaticContentChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static_content_condition.
        /// </summary>
        public static string StaticContentCondition {
            get {
                return ResourceManager.GetString("StaticContentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static_content_valued.
        /// </summary>
        public static string StaticContentValued {
            get {
                return ResourceManager.GetString("StaticContentValued", resourceCulture);
            }
        }
    }
}
