//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSemantics.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameColumns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameColumns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSemantics.Data.GameColumns", typeof(GameColumns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract_entity.
        /// </summary>
        public static string AbstractEntity {
            get {
                return ResourceManager.GetString("AbstractEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation_name.
        /// </summary>
        public static string AnimationName {
            get {
                return ResourceManager.GetString("AnimationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argument.
        /// </summary>
        public static string Argument {
            get {
                return ResourceManager.GetString("Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bounding_box.
        /// </summary>
        public static string BoundingBox {
            get {
                return ResourceManager.GetString("BoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_behavior.
        /// </summary>
        public static string ContentBehavior {
            get {
                return ResourceManager.GetString("ContentBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_change.
        /// </summary>
        public static string ContentChange {
            get {
                return ResourceManager.GetString("ContentChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_condition.
        /// </summary>
        public static string ContentCondition {
            get {
                return ResourceManager.GetString("ContentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_per_view.
        /// </summary>
        public static string ContentPerView {
            get {
                return ResourceManager.GetString("ContentPerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_valued.
        /// </summary>
        public static string ContentValued {
            get {
                return ResourceManager.GetString("ContentValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context_type.
        /// </summary>
        public static string ContextType {
            get {
                return ResourceManager.GetString("ContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cover.
        /// </summary>
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic_content_valued.
        /// </summary>
        public static string DynamicContentValued {
            get {
                return ResourceManager.GetString("DynamicContentValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_content.
        /// </summary>
        public static string EventContent {
            get {
                return ResourceManager.GetString("EventContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_extension.
        /// </summary>
        public static string EventExtension {
            get {
                return ResourceManager.GetString("EventExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_state.
        /// </summary>
        public static string EventState {
            get {
                return ResourceManager.GetString("EventState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter_type.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_animation.
        /// </summary>
        public static string GameAnimation {
            get {
                return ResourceManager.GetString("GameAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_audio.
        /// </summary>
        public static string GameAudio {
            get {
                return ResourceManager.GetString("GameAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_audio_valued.
        /// </summary>
        public static string GameAudioValued {
            get {
                return ResourceManager.GetString("GameAudioValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_material_valued.
        /// </summary>
        public static string GameMaterialValued {
            get {
                return ResourceManager.GetString("GameMaterialValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_node.
        /// </summary>
        public static string GameNode {
            get {
                return ResourceManager.GetString("GameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game_object.
        /// </summary>
        public static string GameObject {
            get {
                return ResourceManager.GetString("GameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_valued.
        /// </summary>
        public static string IconValued {
            get {
                return ResourceManager.GetString("IconValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer.
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loop.
        /// </summary>
        public static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mapping_type.
        /// </summary>
        public static string MappingType {
            get {
                return ResourceManager.GetString("MappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matter_valued.
        /// </summary>
        public static string MatterValued {
            get {
                return ResourceManager.GetString("MatterValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model_animation.
        /// </summary>
        public static string ModelAnimation {
            get {
                return ResourceManager.GetString("ModelAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model_valued.
        /// </summary>
        public static string ModelValued {
            get {
                return ResourceManager.GetString("ModelValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node.
        /// </summary>
        public static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_emitter_valued.
        /// </summary>
        public static string ParticleEmitterValued {
            get {
                return ResourceManager.GetString("ParticleEmitterValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties.
        /// </summary>
        public static string ParticleProperties {
            get {
                return ResourceManager.GetString("ParticleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties_change.
        /// </summary>
        public static string ParticlePropertiesChange {
            get {
                return ResourceManager.GetString("ParticlePropertiesChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties_condition.
        /// </summary>
        public static string ParticlePropertiesCondition {
            get {
                return ResourceManager.GetString("ParticlePropertiesCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_properties_valued.
        /// </summary>
        public static string ParticlePropertiesValued {
            get {
                return ResourceManager.GetString("ParticlePropertiesValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_quantity.
        /// </summary>
        public static string ParticleQuantity {
            get {
                return ResourceManager.GetString("ParticleQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_representation.
        /// </summary>
        public static string ParticleRepresentation {
            get {
                return ResourceManager.GetString("ParticleRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_source.
        /// </summary>
        public static string ParticleSource {
            get {
                return ResourceManager.GetString("ParticleSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle_visualization_file.
        /// </summary>
        public static string ParticleVisualizationFile {
            get {
                return ResourceManager.GetString("ParticleVisualizationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate_type.
        /// </summary>
        public static string PredicateType {
            get {
                return ResourceManager.GetString("PredicateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate_type_to_add.
        /// </summary>
        public static string PredicateTypeToAdd {
            get {
                return ResourceManager.GetString("PredicateTypeToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate_type_to_remove.
        /// </summary>
        public static string PredicateTypeToRemove {
            get {
                return ResourceManager.GetString("PredicateTypeToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotation_change.
        /// </summary>
        public static string RotationChange {
            get {
                return ResourceManager.GetString("RotationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotation_sign.
        /// </summary>
        public static string RotationSign {
            get {
                return ResourceManager.GetString("RotationSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scale_change.
        /// </summary>
        public static string ScaleChange {
            get {
                return ResourceManager.GetString("ScaleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scale_sign.
        /// </summary>
        public static string ScaleSign {
            get {
                return ResourceManager.GetString("ScaleSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed_change.
        /// </summary>
        public static string SpeedChange {
            get {
                return ResourceManager.GetString("SpeedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed_sign.
        /// </summary>
        public static string SpeedSign {
            get {
                return ResourceManager.GetString("SpeedSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprite_valued.
        /// </summary>
        public static string SpriteValued {
            get {
                return ResourceManager.GetString("SpriteValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangible_object.
        /// </summary>
        public static string TangibleObject {
            get {
                return ResourceManager.GetString("TangibleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation_change.
        /// </summary>
        public static string TranslationChange {
            get {
                return ResourceManager.GetString("TranslationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation_sign.
        /// </summary>
        public static string TranslationSign {
            get {
                return ResourceManager.GetString("TranslationSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transparency.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use_models_from_parts.
        /// </summary>
        public static string UseModelsFromParts {
            get {
                return ResourceManager.GetString("UseModelsFromParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view_.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to views_per_context_type.
        /// </summary>
        public static string ViewsPerContextType {
            get {
                return ResourceManager.GetString("ViewsPerContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume_change.
        /// </summary>
        public static string VolumeChange {
            get {
                return ResourceManager.GetString("VolumeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume_sign.
        /// </summary>
        public static string VolumeSign {
            get {
                return ResourceManager.GetString("VolumeSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z_index.
        /// </summary>
        public static string ZIndex {
            get {
                return ResourceManager.GetString("ZIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z_index_change.
        /// </summary>
        public static string ZIndexChange {
            get {
                return ResourceManager.GetString("ZIndexChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z_index_sign.
        /// </summary>
        public static string ZIndexSign {
            get {
                return ResourceManager.GetString("ZIndexSign", resourceCulture);
            }
        }
    }
}
