(define (plan red-cap)
	(:domain red-cap)
	(:problem red-cap)
	(:events
		(1 move redcap motherhouse wolfmeetingspot)
		(2 talk redcap wolf wolfmeetingspot)
		(3 pick-up redcap flowers flowerpickuplocation)
		(4 move wolf wolfmeetingspot insidegrandmotherhouse)
		(5 eat wolf grandmother insidegrandmotherhouse)
		(6 disguise wolf grandmother insidegrandmotherhouse)
		(7 move redcap flowerpickuplocation insidegrandmotherhouse)
		(8 talk redcap wolf insidegrandmotherhouse)
		(9 eat wolf redcap insidegrandmotherhouse)
		(10 move woodman woodmanshouse outsidegrandmotherhouse)
		(11 hears woodman wolf outsidegrandmotherhouse)
		(12 move woodman insidegrandmotherhouse outsidegrandmotherhouse)
		(13 cuts-open woodman wolf insidegrandmotherhouse)
		(14 skin woodman wolf insidegrandmotherhouse)
		(15 pick-up woodman wolfskin insidegrandmotherhouse)
		(16 move woodman insidegrandmotherhouse outsidegrandmotherhouse)
		(17 move woodman outsidegrandmotherhouse woodmanshouse)
		(18 eat redcap goodies insidegrandmotherhouse)
		(19 eat grandmother goodies insidegrandmotherhouse)
	)
)