//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantics.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantics.Utilities.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        internal static string ActorTarget_Actor {
            get {
                return ResourceManager.GetString("ActorTarget_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string ActorTarget_Target {
            get {
                return ResourceManager.GetString("ActorTarget_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        internal static string ActorTargetArtifact_Actor {
            get {
                return ResourceManager.GetString("ActorTargetArtifact_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact.
        /// </summary>
        internal static string ActorTargetArtifact_Artifact {
            get {
                return ResourceManager.GetString("ActorTargetArtifact_Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string ActorTargetArtifact_Target {
            get {
                return ResourceManager.GetString("ActorTargetArtifact_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        internal static string ActorTargetArtifactReference_Actor {
            get {
                return ResourceManager.GetString("ActorTargetArtifactReference_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact.
        /// </summary>
        internal static string ActorTargetArtifactReference_Artifact {
            get {
                return ResourceManager.GetString("ActorTargetArtifactReference_Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string ActorTargetArtifactReference_Reference {
            get {
                return ResourceManager.GetString("ActorTargetArtifactReference_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string ActorTargetArtifactReference_Target {
            get {
                return ResourceManager.GetString("ActorTargetArtifactReference_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant.
        /// </summary>
        internal static string AttributeType_Constant {
            get {
                return ResourceManager.GetString("AttributeType_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent.
        /// </summary>
        internal static string AttributeType_Dependent {
            get {
                return ResourceManager.GetString("AttributeType_Dependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutable.
        /// </summary>
        internal static string AttributeType_Mutable {
            get {
                return ResourceManager.GetString("AttributeType_Mutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        internal static string BinaryOperator_Complement {
            get {
                return ResourceManager.GetString("BinaryOperator_Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection.
        /// </summary>
        internal static string BinaryOperator_Intersection {
            get {
                return ResourceManager.GetString("BinaryOperator_Intersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric difference.
        /// </summary>
        internal static string BinaryOperator_SymmetricDifference {
            get {
                return ResourceManager.GetString("BinaryOperator_SymmetricDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union.
        /// </summary>
        internal static string BinaryOperator_Union {
            get {
                return ResourceManager.GetString("BinaryOperator_Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string BooleanType_False {
            get {
                return ResourceManager.GetString("BooleanType_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string BooleanType_True {
            get {
                return ResourceManager.GetString("BooleanType_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many-to-many.
        /// </summary>
        internal static string Cardinality_ManyToMany {
            get {
                return ResourceManager.GetString("Cardinality_ManyToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many-to-one.
        /// </summary>
        internal static string Cardinality_ManyToOne {
            get {
                return ResourceManager.GetString("Cardinality_ManyToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-to-many.
        /// </summary>
        internal static string Cardinality_OneToMany {
            get {
                return ResourceManager.GetString("Cardinality_OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-to-one.
        /// </summary>
        internal static string Cardinality_OneToOne {
            get {
                return ResourceManager.GetString("Cardinality_OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heterogeneous.
        /// </summary>
        internal static string Composition_Heterogeneous {
            get {
                return ResourceManager.GetString("Composition_Heterogeneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homogeneous.
        /// </summary>
        internal static string Composition_Homogeneous {
            get {
                return ResourceManager.GetString("Composition_Homogeneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string CountType_Connections {
            get {
                return ResourceManager.GetString("CountType_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covers.
        /// </summary>
        internal static string CountType_Covers {
            get {
                return ResourceManager.GetString("CountType_Covers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        internal static string CountType_Everything {
            get {
                return ResourceManager.GetString("CountType_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string CountType_Layers {
            get {
                return ResourceManager.GetString("CountType_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string CountType_Parts {
            get {
                return ResourceManager.GetString("CountType_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space items.
        /// </summary>
        internal static string CountType_SpaceItems {
            get {
                return ResourceManager.GetString("CountType_SpaceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        internal static string CountType_Spaces {
            get {
                return ResourceManager.GetString("CountType_Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity as source, actor as target.
        /// </summary>
        internal static string CreationRelationshipSourceTarget_RelateEntityAsSourceAndActorAsTarget {
            get {
                return ResourceManager.GetString("CreationRelationshipSourceTarget_RelateEntityAsSourceAndActorAsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity as source, target as target.
        /// </summary>
        internal static string CreationRelationshipSourceTarget_RelateEntityAsSourceAndTargetAsTarget {
            get {
                return ResourceManager.GetString("CreationRelationshipSourceTarget_RelateEntityAsSourceAndTargetAsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity as target, actor as source.
        /// </summary>
        internal static string CreationRelationshipSourceTarget_RelateEntityAsTargetAndActorAsSource {
            get {
                return ResourceManager.GetString("CreationRelationshipSourceTarget_RelateEntityAsTargetAndActorAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity as target, target as source.
        /// </summary>
        internal static string CreationRelationshipSourceTarget_RelateEntityAsTargetAndTargetAsSource {
            get {
                return ResourceManager.GetString("CreationRelationshipSourceTarget_RelateEntityAsTargetAndTargetAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined at quantity.
        /// </summary>
        internal static string DeletionType_DefinedAtQuantity {
            get {
                return ResourceManager.GetString("DeletionType_DefinedAtQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        internal static string DeletionType_DeleteAll {
            get {
                return ResourceManager.GetString("DeletionType_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        internal static string DesiredValueType_Between {
            get {
                return ResourceManager.GetString("DesiredValueType_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string DesiredValueType_Decrease {
            get {
                return ResourceManager.GetString("DesiredValueType_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease between.
        /// </summary>
        internal static string DesiredValueType_DecreaseBetween {
            get {
                return ResourceManager.GetString("DesiredValueType_DecreaseBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease by at least.
        /// </summary>
        internal static string DesiredValueType_DecreaseByAtLeast {
            get {
                return ResourceManager.GetString("DesiredValueType_DecreaseByAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease by at most.
        /// </summary>
        internal static string DesiredValueType_DecreaseByAtMost {
            get {
                return ResourceManager.GetString("DesiredValueType_DecreaseByAtMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        internal static string DesiredValueType_Equal {
            get {
                return ResourceManager.GetString("DesiredValueType_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        internal static string DesiredValueType_Greater {
            get {
                return ResourceManager.GetString("DesiredValueType_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal to.
        /// </summary>
        internal static string DesiredValueType_GreaterOrEqual {
            get {
                return ResourceManager.GetString("DesiredValueType_GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string DesiredValueType_Increase {
            get {
                return ResourceManager.GetString("DesiredValueType_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase between.
        /// </summary>
        internal static string DesiredValueType_IncreaseBetween {
            get {
                return ResourceManager.GetString("DesiredValueType_IncreaseBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase by at least.
        /// </summary>
        internal static string DesiredValueType_IncreaseByAtLeast {
            get {
                return ResourceManager.GetString("DesiredValueType_IncreaseByAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase by at most.
        /// </summary>
        internal static string DesiredValueType_IncreaseByAtMost {
            get {
                return ResourceManager.GetString("DesiredValueType_IncreaseByAtMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower than.
        /// </summary>
        internal static string DesiredValueType_Lower {
            get {
                return ResourceManager.GetString("DesiredValueType_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower than or equal to.
        /// </summary>
        internal static string DesiredValueType_LowerOrEqual {
            get {
                return ResourceManager.GetString("DesiredValueType_LowerOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to.
        /// </summary>
        internal static string DesiredValueType_NotEqual {
            get {
                return ResourceManager.GetString("DesiredValueType_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covers of actor.
        /// </summary>
        internal static string Destination_ActorCovers {
            get {
                return ResourceManager.GetString("Destination_ActorCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements of actor.
        /// </summary>
        internal static string Destination_ActorElements {
            get {
                return ResourceManager.GetString("Destination_ActorElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items of actor.
        /// </summary>
        internal static string Destination_ActorItems {
            get {
                return ResourceManager.GetString("Destination_ActorItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers of actor.
        /// </summary>
        internal static string Destination_ActorLayers {
            get {
                return ResourceManager.GetString("Destination_ActorLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts of actor.
        /// </summary>
        internal static string Destination_ActorParts {
            get {
                return ResourceManager.GetString("Destination_ActorParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces of actor.
        /// </summary>
        internal static string Destination_ActorSpaces {
            get {
                return ResourceManager.GetString("Destination_ActorSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substances of actor.
        /// </summary>
        internal static string Destination_ActorSubstances {
            get {
                return ResourceManager.GetString("Destination_ActorSubstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covers of target.
        /// </summary>
        internal static string Destination_TargetCovers {
            get {
                return ResourceManager.GetString("Destination_TargetCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements of target.
        /// </summary>
        internal static string Destination_TargetElements {
            get {
                return ResourceManager.GetString("Destination_TargetElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items of target.
        /// </summary>
        internal static string Destination_TargetItems {
            get {
                return ResourceManager.GetString("Destination_TargetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers of target.
        /// </summary>
        internal static string Destination_TargetLayers {
            get {
                return ResourceManager.GetString("Destination_TargetLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts of target.
        /// </summary>
        internal static string Destination_TargetParts {
            get {
                return ResourceManager.GetString("Destination_TargetParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces of target.
        /// </summary>
        internal static string Destination_TargetSpaces {
            get {
                return ResourceManager.GetString("Destination_TargetSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substances of target.
        /// </summary>
        internal static string Destination_TargetSubstances {
            get {
                return ResourceManager.GetString("Destination_TargetSubstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string Destination_World {
            get {
                return ResourceManager.GetString("Destination_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string DurationType_Fixed {
            get {
                return ResourceManager.GetString("DurationType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed, dependent on requirements.
        /// </summary>
        internal static string DurationType_FixedDependentOnRequirements {
            get {
                return ResourceManager.GetString("DurationType_FixedDependentOnRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite.
        /// </summary>
        internal static string DurationType_Infinite {
            get {
                return ResourceManager.GetString("DurationType_Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite, dependent on requirements.
        /// </summary>
        internal static string DurationType_InfiniteDependentOnRequirements {
            get {
                return ResourceManager.GetString("DurationType_InfiniteDependentOnRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string ElementBlock_D {
            get {
                return ResourceManager.GetString("ElementBlock_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string ElementBlock_F {
            get {
                return ResourceManager.GetString("ElementBlock_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string ElementBlock_G {
            get {
                return ResourceManager.GetString("ElementBlock_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string ElementBlock_P {
            get {
                return ResourceManager.GetString("ElementBlock_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string ElementBlock_S {
            get {
                return ResourceManager.GetString("ElementBlock_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string ElementGroup_Eight {
            get {
                return ResourceManager.GetString("ElementGroup_Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string ElementGroup_Eighteen {
            get {
                return ResourceManager.GetString("ElementGroup_Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string ElementGroup_Eleven {
            get {
                return ResourceManager.GetString("ElementGroup_Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string ElementGroup_Fifteen {
            get {
                return ResourceManager.GetString("ElementGroup_Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ElementGroup_Five {
            get {
                return ResourceManager.GetString("ElementGroup_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string ElementGroup_Four {
            get {
                return ResourceManager.GetString("ElementGroup_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string ElementGroup_Fourteen {
            get {
                return ResourceManager.GetString("ElementGroup_Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string ElementGroup_Nine {
            get {
                return ResourceManager.GetString("ElementGroup_Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ElementGroup_One {
            get {
                return ResourceManager.GetString("ElementGroup_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string ElementGroup_Seven {
            get {
                return ResourceManager.GetString("ElementGroup_Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string ElementGroup_Seventeen {
            get {
                return ResourceManager.GetString("ElementGroup_Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string ElementGroup_Six {
            get {
                return ResourceManager.GetString("ElementGroup_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string ElementGroup_Sixteen {
            get {
                return ResourceManager.GetString("ElementGroup_Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ElementGroup_Ten {
            get {
                return ResourceManager.GetString("ElementGroup_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ElementGroup_Thirteen {
            get {
                return ResourceManager.GetString("ElementGroup_Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ElementGroup_Three {
            get {
                return ResourceManager.GetString("ElementGroup_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string ElementGroup_Twelve {
            get {
                return ResourceManager.GetString("ElementGroup_Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ElementGroup_Two {
            get {
                return ResourceManager.GetString("ElementGroup_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string ElementPeriod_Eight {
            get {
                return ResourceManager.GetString("ElementPeriod_Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ElementPeriod_Five {
            get {
                return ResourceManager.GetString("ElementPeriod_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string ElementPeriod_Four {
            get {
                return ResourceManager.GetString("ElementPeriod_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ElementPeriod_One {
            get {
                return ResourceManager.GetString("ElementPeriod_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string ElementPeriod_Seven {
            get {
                return ResourceManager.GetString("ElementPeriod_Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string ElementPeriod_Six {
            get {
                return ResourceManager.GetString("ElementPeriod_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ElementPeriod_Three {
            get {
                return ResourceManager.GetString("ElementPeriod_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ElementPeriod_Two {
            get {
                return ResourceManager.GetString("ElementPeriod_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        internal static string ElementType_Metal {
            get {
                return ResourceManager.GetString("ElementType_Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metalloid.
        /// </summary>
        internal static string ElementType_Metalloid {
            get {
                return ResourceManager.GetString("ElementType_Metalloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-metal.
        /// </summary>
        internal static string ElementType_Nonmetal {
            get {
                return ResourceManager.GetString("ElementType_Nonmetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==.
        /// </summary>
        internal static string EqualitySign_Equal {
            get {
                return ResourceManager.GetString("EqualitySign_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !=.
        /// </summary>
        internal static string EqualitySign_NotEqual {
            get {
                return ResourceManager.GetString("EqualitySign_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==.
        /// </summary>
        internal static string EqualitySignExtended_Equal {
            get {
                return ResourceManager.GetString("EqualitySignExtended_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string EqualitySignExtended_Greater {
            get {
                return ResourceManager.GetString("EqualitySignExtended_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string EqualitySignExtended_GreaterOrEqual {
            get {
                return ResourceManager.GetString("EqualitySignExtended_GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string EqualitySignExtended_Lower {
            get {
                return ResourceManager.GetString("EqualitySignExtended_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string EqualitySignExtended_LowerOrEqual {
            get {
                return ResourceManager.GetString("EqualitySignExtended_LowerOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !=.
        /// </summary>
        internal static string EqualitySignExtended_NotEqual {
            get {
                return ResourceManager.GetString("EqualitySignExtended_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [...].
        /// </summary>
        internal static string EqualitySignExtendedDual_Between {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==.
        /// </summary>
        internal static string EqualitySignExtendedDual_Equal {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string EqualitySignExtendedDual_Greater {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string EqualitySignExtendedDual_GreaterOrEqual {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string EqualitySignExtendedDual_Lower {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string EqualitySignExtendedDual_LowerOrEqual {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_LowerOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! [...].
        /// </summary>
        internal static string EqualitySignExtendedDual_NotBetween {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_NotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !=.
        /// </summary>
        internal static string EqualitySignExtendedDual_NotEqual {
            get {
                return ResourceManager.GetString("EqualitySignExtendedDual_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string EventBehavior_Automatic {
            get {
                return ResourceManager.GetString("EventBehavior_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string EventBehavior_Manual {
            get {
                return ResourceManager.GetString("EventBehavior_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event starts.
        /// </summary>
        internal static string EventState_Starts {
            get {
                return ResourceManager.GetString("EventState_Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event stops.
        /// </summary>
        internal static string EventState_Stops {
            get {
                return ResourceManager.GetString("EventState_Stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string FrequencyType_Fixed {
            get {
                return ResourceManager.GetString("FrequencyType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite.
        /// </summary>
        internal static string FrequencyType_Infinite {
            get {
                return ResourceManager.GetString("FrequencyType_Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs.
        /// </summary>
        internal static string Function_Absolute {
            get {
                return ResourceManager.GetString("Function_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acos.
        /// </summary>
        internal static string Function_Acosine {
            get {
                return ResourceManager.GetString("Function_Acosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asin.
        /// </summary>
        internal static string Function_Asine {
            get {
                return ResourceManager.GetString("Function_Asine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atan.
        /// </summary>
        internal static string Function_Atangent {
            get {
                return ResourceManager.GetString("Function_Atangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceiling.
        /// </summary>
        internal static string Function_Ceiling {
            get {
                return ResourceManager.GetString("Function_Ceiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cos.
        /// </summary>
        internal static string Function_Cosine {
            get {
                return ResourceManager.GetString("Function_Cosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp.
        /// </summary>
        internal static string Function_Exponent {
            get {
                return ResourceManager.GetString("Function_Exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to floor.
        /// </summary>
        internal static string Function_Floor {
            get {
                return ResourceManager.GetString("Function_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log10.
        /// </summary>
        internal static string Function_Log10 {
            get {
                return ResourceManager.GetString("Function_Log10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln.
        /// </summary>
        internal static string Function_NaturalLogarithm {
            get {
                return ResourceManager.GetString("Function_NaturalLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        internal static string Function_Round {
            get {
                return ResourceManager.GetString("Function_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin.
        /// </summary>
        internal static string Function_Sine {
            get {
                return ResourceManager.GetString("Function_Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqrt.
        /// </summary>
        internal static string Function_SquareRoot {
            get {
                return ResourceManager.GetString("Function_SquareRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan.
        /// </summary>
        internal static string Function_Tangent {
            get {
                return ResourceManager.GetString("Function_Tangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string LogicalOperator_And {
            get {
                return ResourceManager.GetString("LogicalOperator_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LogicalOperator_None {
            get {
                return ResourceManager.GetString("LogicalOperator_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string LogicalOperator_Or {
            get {
                return ResourceManager.GetString("LogicalOperator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string MetalType_Base {
            get {
                return ResourceManager.GetString("MetalType_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrous.
        /// </summary>
        internal static string MetalType_Ferrous {
            get {
                return ResourceManager.GetString("MetalType_Ferrous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        internal static string MetalType_Noble {
            get {
                return ResourceManager.GetString("MetalType_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precious.
        /// </summary>
        internal static string MetalType_Precious {
            get {
                return ResourceManager.GetString("MetalType_Precious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloy.
        /// </summary>
        internal static string MixtureType_Alloy {
            get {
                return ResourceManager.GetString("MixtureType_Alloy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colloid.
        /// </summary>
        internal static string MixtureType_Colloid {
            get {
                return ResourceManager.GetString("MixtureType_Colloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string MixtureType_Solution {
            get {
                return ResourceManager.GetString("MixtureType_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension.
        /// </summary>
        internal static string MixtureType_Suspension {
            get {
                return ResourceManager.GetString("MixtureType_Suspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string Necessity_Mandatory {
            get {
                return ResourceManager.GetString("Necessity_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string Necessity_Optional {
            get {
                return ResourceManager.GetString("Necessity_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string Operator_Addition {
            get {
                return ResourceManager.GetString("Operator_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string Operator_Division {
            get {
                return ResourceManager.GetString("Operator_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Operator_Multiplication {
            get {
                return ResourceManager.GetString("Operator_Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        internal static string Operator_Power {
            get {
                return ResourceManager.GetString("Operator_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Operator_Subtraction {
            get {
                return ResourceManager.GetString("Operator_Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant of layer.
        /// </summary>
        internal static string OwnerType_ApplicantOfLayer {
            get {
                return ResourceManager.GetString("OwnerType_ApplicantOfLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound of substance.
        /// </summary>
        internal static string OwnerType_CompoundOfSubstance {
            get {
                return ResourceManager.GetString("OwnerType_CompoundOfSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered object of cover.
        /// </summary>
        internal static string OwnerType_CoveredObjectOfCover {
            get {
                return ResourceManager.GetString("OwnerType_CoveredObjectOfCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixture of substance.
        /// </summary>
        internal static string OwnerType_MixtureOfSubstance {
            get {
                return ResourceManager.GetString("OwnerType_MixtureOfSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical object of space.
        /// </summary>
        internal static string OwnerType_PhysicalObjectOfSpace {
            get {
                return ResourceManager.GetString("OwnerType_PhysicalObjectOfSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space of item.
        /// </summary>
        internal static string OwnerType_SpaceOfItem {
            get {
                return ResourceManager.GetString("OwnerType_SpaceOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space of matter.
        /// </summary>
        internal static string OwnerType_SpaceOfMatter {
            get {
                return ResourceManager.GetString("OwnerType_SpaceOfMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangible object of matter.
        /// </summary>
        internal static string OwnerType_TangibleObjectOfMatter {
            get {
                return ResourceManager.GetString("OwnerType_TangibleObjectOfMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole of part.
        /// </summary>
        internal static string OwnerType_WholeOfPart {
            get {
                return ResourceManager.GetString("OwnerType_WholeOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atto.
        /// </summary>
        internal static string Prefix_Atto {
            get {
                return ResourceManager.GetString("Prefix_Atto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centi.
        /// </summary>
        internal static string Prefix_Centi {
            get {
                return ResourceManager.GetString("Prefix_Centi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deca.
        /// </summary>
        internal static string Prefix_Deca {
            get {
                return ResourceManager.GetString("Prefix_Deca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deci.
        /// </summary>
        internal static string Prefix_Deci {
            get {
                return ResourceManager.GetString("Prefix_Deci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exa.
        /// </summary>
        internal static string Prefix_Exa {
            get {
                return ResourceManager.GetString("Prefix_Exa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to femto.
        /// </summary>
        internal static string Prefix_Femto {
            get {
                return ResourceManager.GetString("Prefix_Femto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giga.
        /// </summary>
        internal static string Prefix_Giga {
            get {
                return ResourceManager.GetString("Prefix_Giga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hecto.
        /// </summary>
        internal static string Prefix_Hecto {
            get {
                return ResourceManager.GetString("Prefix_Hecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilo.
        /// </summary>
        internal static string Prefix_Kilo {
            get {
                return ResourceManager.GetString("Prefix_Kilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.
        /// </summary>
        internal static string Prefix_Mega {
            get {
                return ResourceManager.GetString("Prefix_Mega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to micro.
        /// </summary>
        internal static string Prefix_Micro {
            get {
                return ResourceManager.GetString("Prefix_Micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli.
        /// </summary>
        internal static string Prefix_Milli {
            get {
                return ResourceManager.GetString("Prefix_Milli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nano.
        /// </summary>
        internal static string Prefix_Nano {
            get {
                return ResourceManager.GetString("Prefix_Nano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prefix_None {
            get {
                return ResourceManager.GetString("Prefix_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peta.
        /// </summary>
        internal static string Prefix_Peta {
            get {
                return ResourceManager.GetString("Prefix_Peta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pico.
        /// </summary>
        internal static string Prefix_Pico {
            get {
                return ResourceManager.GetString("Prefix_Pico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tera.
        /// </summary>
        internal static string Prefix_Tera {
            get {
                return ResourceManager.GetString("Prefix_Tera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yocto.
        /// </summary>
        internal static string Prefix_Yocto {
            get {
                return ResourceManager.GetString("Prefix_Yocto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yotta.
        /// </summary>
        internal static string Prefix_Yotta {
            get {
                return ResourceManager.GetString("Prefix_Yotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zepto.
        /// </summary>
        internal static string Prefix_Zepto {
            get {
                return ResourceManager.GetString("Prefix_Zepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zetta.
        /// </summary>
        internal static string Prefix_Zetta {
            get {
                return ResourceManager.GetString("Prefix_Zetta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached.
        /// </summary>
        internal static string Presence_Attached {
            get {
                return ResourceManager.GetString("Presence_Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string Presence_Present {
            get {
                return ResourceManager.GetString("Presence_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities in radius.
        /// </summary>
        internal static string RangeType_EntitiesInRadius {
            get {
                return ResourceManager.GetString("RangeType_EntitiesInRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities only.
        /// </summary>
        internal static string RangeType_EntitiesOnly {
            get {
                return ResourceManager.GetString("RangeType_EntitiesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius only.
        /// </summary>
        internal static string RangeType_RadiusOnly {
            get {
                return ResourceManager.GetString("RangeType_RadiusOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SelectionType_All {
            get {
                return ResourceManager.GetString("SelectionType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farthest.
        /// </summary>
        internal static string SelectionType_Farthest {
            get {
                return ResourceManager.GetString("SelectionType_Farthest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest.
        /// </summary>
        internal static string SelectionType_Nearest {
            get {
                return ResourceManager.GetString("SelectionType_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string SelectionType_Random {
            get {
                return ResourceManager.GetString("SelectionType_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SourceTarget_Source {
            get {
                return ResourceManager.GetString("SourceTarget_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string SourceTarget_Target {
            get {
                return ResourceManager.GetString("SourceTarget_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string SpaceType_Closed {
            get {
                return ResourceManager.GetString("SpaceType_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        internal static string SpaceType_Open {
            get {
                return ResourceManager.GetString("SpaceType_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string SpecialAttributes_Position {
            get {
                return ResourceManager.GetString("SpecialAttributes_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string SpecialAttributes_Rotation {
            get {
                return ResourceManager.GetString("SpecialAttributes_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string SpecialAttributes_Scale {
            get {
                return ResourceManager.GetString("SpecialAttributes_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string SpecialUnitCategories_Distance {
            get {
                return ResourceManager.GetString("SpecialUnitCategories_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string SpecialUnitCategories_Quantity {
            get {
                return ResourceManager.GetString("SpecialUnitCategories_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string SpecialUnitCategories_Time {
            get {
                return ResourceManager.GetString("SpecialUnitCategories_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        internal static string StateOfMatter_Gas {
            get {
                return ResourceManager.GetString("StateOfMatter_Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid.
        /// </summary>
        internal static string StateOfMatter_Liquid {
            get {
                return ResourceManager.GetString("StateOfMatter_Liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma.
        /// </summary>
        internal static string StateOfMatter_Plasma {
            get {
                return ResourceManager.GetString("StateOfMatter_Plasma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string StateOfMatter_Solid {
            get {
                return ResourceManager.GetString("StateOfMatter_Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string StorageType_Capacity {
            get {
                return ResourceManager.GetString("StorageType_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. nr. of items.
        /// </summary>
        internal static string StorageType_MaximumNumberOfItems {
            get {
                return ResourceManager.GetString("StorageType_MaximumNumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. of items and capacity.
        /// </summary>
        internal static string StorageType_MaximumNumberOfItemsAndCapacity {
            get {
                return ResourceManager.GetString("StorageType_MaximumNumberOfItemsAndCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string StorageType_Unlimited {
            get {
                return ResourceManager.GetString("StorageType_Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        internal static string TimeType_Continuous {
            get {
                return ResourceManager.GetString("TimeType_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete.
        /// </summary>
        internal static string TimeType_Discrete {
            get {
                return ResourceManager.GetString("TimeType_Discrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor to actor.
        /// </summary>
        internal static string TransferDirection_ActorToActor {
            get {
                return ResourceManager.GetString("TransferDirection_ActorToActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor to target.
        /// </summary>
        internal static string TransferDirection_ActorToTarget {
            get {
                return ResourceManager.GetString("TransferDirection_ActorToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target to actor.
        /// </summary>
        internal static string TransferDirection_TargetToActor {
            get {
                return ResourceManager.GetString("TransferDirection_TargetToActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target to target.
        /// </summary>
        internal static string TransferDirection_TargetToTarget {
            get {
                return ResourceManager.GetString("TransferDirection_TargetToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor to target.
        /// </summary>
        internal static string TransferType_ActorToTarget {
            get {
                return ResourceManager.GetString("TransferType_ActorToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string TransferType_Items {
            get {
                return ResourceManager.GetString("TransferType_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target to actor.
        /// </summary>
        internal static string TransferType_TargetToActor {
            get {
                return ResourceManager.GetString("TransferType_TargetToActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease by.
        /// </summary>
        internal static string ValueChangeType_Decrease {
            get {
                return ResourceManager.GetString("ValueChangeType_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide by.
        /// </summary>
        internal static string ValueChangeType_Divide {
            get {
                return ResourceManager.GetString("ValueChangeType_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equate to.
        /// </summary>
        internal static string ValueChangeType_Equate {
            get {
                return ResourceManager.GetString("ValueChangeType_Equate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase by.
        /// </summary>
        internal static string ValueChangeType_Increase {
            get {
                return ResourceManager.GetString("ValueChangeType_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply by.
        /// </summary>
        internal static string ValueChangeType_Multiply {
            get {
                return ResourceManager.GetString("ValueChangeType_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string ValueType_Boolean {
            get {
                return ResourceManager.GetString("ValueType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical.
        /// </summary>
        internal static string ValueType_Numerical {
            get {
                return ResourceManager.GetString("ValueType_Numerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string ValueType_String {
            get {
                return ResourceManager.GetString("ValueType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string ValueType_Term {
            get {
                return ResourceManager.GetString("ValueType_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector.
        /// </summary>
        internal static string ValueType_Vector {
            get {
                return ResourceManager.GetString("ValueType_Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string VariableType_Attribute {
            get {
                return ResourceManager.GetString("VariableType_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string VariableType_Count {
            get {
                return ResourceManager.GetString("VariableType_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string VariableType_Distance {
            get {
                return ResourceManager.GetString("VariableType_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string VariableType_Fixed {
            get {
                return ResourceManager.GetString("VariableType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string VariableType_Quantity {
            get {
                return ResourceManager.GetString("VariableType_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires manual input.
        /// </summary>
        internal static string VariableType_RequiresManualInput {
            get {
                return ResourceManager.GetString("VariableType_RequiresManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string VariableType_Sum {
            get {
                return ResourceManager.GetString("VariableType_Sum", resourceCulture);
            }
        }
    }
}
