//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantics.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantics.Utilities.NewNames", typeof(NewNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract entity.
        /// </summary>
        public static string AbstractEntity {
            get {
                return ResourceManager.GetString("AbstractEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract entity change.
        /// </summary>
        public static string AbstractEntityChange {
            get {
                return ResourceManager.GetString("AbstractEntityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract entity condition.
        /// </summary>
        public static string AbstractEntityCondition {
            get {
                return ResourceManager.GetString("AbstractEntityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute change.
        /// </summary>
        public static string AttributeChange {
            get {
                return ResourceManager.GetString("AttributeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute condition.
        /// </summary>
        public static string AttributeCondition {
            get {
                return ResourceManager.GetString("AttributeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bool variable.
        /// </summary>
        public static string BoolVariable {
            get {
                return ResourceManager.GetString("BoolVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined relationship.
        /// </summary>
        public static string CombinedRelationship {
            get {
                return ResourceManager.GetString("CombinedRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound.
        /// </summary>
        public static string Compound {
            get {
                return ResourceManager.GetString("Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound change.
        /// </summary>
        public static string CompoundChange {
            get {
                return ResourceManager.GetString("CompoundChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound condition.
        /// </summary>
        public static string CompoundCondition {
            get {
                return ResourceManager.GetString("CompoundCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection item change.
        /// </summary>
        public static string ConnectionItemChange {
            get {
                return ResourceManager.GetString("ConnectionItemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection item condition.
        /// </summary>
        public static string ConnectionItemCondition {
            get {
                return ResourceManager.GetString("ConnectionItemCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection reference.
        /// </summary>
        public static string ConnectionReference {
            get {
                return ResourceManager.GetString("ConnectionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context type.
        /// </summary>
        public static string ContextType {
            get {
                return ResourceManager.GetString("ContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover change.
        /// </summary>
        public static string CoverChange {
            get {
                return ResourceManager.GetString("CoverChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover condition.
        /// </summary>
        public static string CoverCondition {
            get {
                return ResourceManager.GetString("CoverCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover reference.
        /// </summary>
        public static string CoverReference {
            get {
                return ResourceManager.GetString("CoverReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        public static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        public static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element change.
        /// </summary>
        public static string ElementChange {
            get {
                return ResourceManager.GetString("ElementChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element condition.
        /// </summary>
        public static string ElementCondition {
            get {
                return ResourceManager.GetString("ElementCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string EntityCreation {
            get {
                return ResourceManager.GetString("EntityCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter application.
        /// </summary>
        public static string FilterApplication {
            get {
                return ResourceManager.GetString("FilterApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter type.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item reference.
        /// </summary>
        public static string ItemReference {
            get {
                return ResourceManager.GetString("ItemReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer change.
        /// </summary>
        public static string LayerChange {
            get {
                return ResourceManager.GetString("LayerChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer condition.
        /// </summary>
        public static string LayerCondition {
            get {
                return ResourceManager.GetString("LayerCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer reference.
        /// </summary>
        public static string LayerReference {
            get {
                return ResourceManager.GetString("LayerReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material change.
        /// </summary>
        public static string MaterialChange {
            get {
                return ResourceManager.GetString("MaterialChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material condition.
        /// </summary>
        public static string MaterialCondition {
            get {
                return ResourceManager.GetString("MaterialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter reference.
        /// </summary>
        public static string MatterReference {
            get {
                return ResourceManager.GetString("MatterReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixture.
        /// </summary>
        public static string Mixture {
            get {
                return ResourceManager.GetString("Mixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixture change.
        /// </summary>
        public static string MixtureChange {
            get {
                return ResourceManager.GetString("MixtureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixture condition.
        /// </summary>
        public static string MixtureCondition {
            get {
                return ResourceManager.GetString("MixtureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node change.
        /// </summary>
        public static string NodeChange {
            get {
                return ResourceManager.GetString("NodeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node condition.
        /// </summary>
        public static string NodeCondition {
            get {
                return ResourceManager.GetString("NodeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical variable.
        /// </summary>
        public static string NumericalVariable {
            get {
                return ResourceManager.GetString("NumericalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner reference.
        /// </summary>
        public static string OwnerReference {
            get {
                return ResourceManager.GetString("OwnerReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part change.
        /// </summary>
        public static string PartChange {
            get {
                return ResourceManager.GetString("PartChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part condition.
        /// </summary>
        public static string PartCondition {
            get {
                return ResourceManager.GetString("PartCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part reference.
        /// </summary>
        public static string PartReference {
            get {
                return ResourceManager.GetString("PartReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical object.
        /// </summary>
        public static string PhysicalObject {
            get {
                return ResourceManager.GetString("PhysicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate.
        /// </summary>
        public static string Predicate {
            get {
                return ResourceManager.GetString("Predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate type.
        /// </summary>
        public static string PredicateType {
            get {
                return ResourceManager.GetString("PredicateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random variable.
        /// </summary>
        public static string RandomVariable {
            get {
                return ResourceManager.GetString("RandomVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction.
        /// </summary>
        public static string Reaction {
            get {
                return ResourceManager.GetString("Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship change.
        /// </summary>
        public static string RelationshipChange {
            get {
                return ResourceManager.GetString("RelationshipChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship condition.
        /// </summary>
        public static string RelationshipCondition {
            get {
                return ResourceManager.GetString("RelationshipCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship establishment.
        /// </summary>
        public static string RelationshipEstablishment {
            get {
                return ResourceManager.GetString("RelationshipEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship reference.
        /// </summary>
        public static string RelationshipReference {
            get {
                return ResourceManager.GetString("RelationshipReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship type.
        /// </summary>
        public static string RelationshipType {
            get {
                return ResourceManager.GetString("RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set reference.
        /// </summary>
        public static string SetReference {
            get {
                return ResourceManager.GetString("SetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space change.
        /// </summary>
        public static string SpaceChange {
            get {
                return ResourceManager.GetString("SpaceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space condition.
        /// </summary>
        public static string SpaceCondition {
            get {
                return ResourceManager.GetString("SpaceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space reference.
        /// </summary>
        public static string SpaceReference {
            get {
                return ResourceManager.GetString("SpaceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial reference.
        /// </summary>
        public static string SpatialReference {
            get {
                return ResourceManager.GetString("SpatialReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State group.
        /// </summary>
        public static string StateGroup {
            get {
                return ResourceManager.GetString("StateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State group change.
        /// </summary>
        public static string StateGroupChange {
            get {
                return ResourceManager.GetString("StateGroupChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State group condition.
        /// </summary>
        public static string StateGroupCondition {
            get {
                return ResourceManager.GetString("StateGroupCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String variable.
        /// </summary>
        public static string StringVariable {
            get {
                return ResourceManager.GetString("StringVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substance.
        /// </summary>
        public static string Substance {
            get {
                return ResourceManager.GetString("Substance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substance change.
        /// </summary>
        public static string SubstanceChange {
            get {
                return ResourceManager.GetString("SubstanceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substance condition.
        /// </summary>
        public static string SubstanceCondition {
            get {
                return ResourceManager.GetString("SubstanceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangible object.
        /// </summary>
        public static string TangibleObject {
            get {
                return ResourceManager.GetString("TangibleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangible object change.
        /// </summary>
        public static string TangibleObjectChange {
            get {
                return ResourceManager.GetString("TangibleObjectChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangible object condition.
        /// </summary>
        public static string TangibleObjectCondition {
            get {
                return ResourceManager.GetString("TangibleObjectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term variable.
        /// </summary>
        public static string TermVariable {
            get {
                return ResourceManager.GetString("TermVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        public static string Transformation {
            get {
                return ResourceManager.GetString("Transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit category.
        /// </summary>
        public static string UnitCategory {
            get {
                return ResourceManager.GetString("UnitCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector variable.
        /// </summary>
        public static string VectorVariable {
            get {
                return ResourceManager.GetString("VectorVariable", resourceCulture);
            }
        }
    }
}
