//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSemantics.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSemantics.Utilities.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is executing.
        /// </summary>
        internal static string EventStateExtended_IsExecuting {
            get {
                return ResourceManager.GetString("EventStateExtended_IsExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts.
        /// </summary>
        internal static string EventStateExtended_Starts {
            get {
                return ResourceManager.GetString("EventStateExtended_Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops.
        /// </summary>
        internal static string EventStateExtended_Stops {
            get {
                return ResourceManager.GetString("EventStateExtended_Stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ParticleRepresentation_File {
            get {
                return ResourceManager.GetString("ParticleRepresentation_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangible matter.
        /// </summary>
        internal static string ParticleRepresentation_TangibleMatter {
            get {
                return ResourceManager.GetString("ParticleRepresentation_TangibleMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangible object.
        /// </summary>
        internal static string ParticleRepresentation_TangibleObject {
            get {
                return ResourceManager.GetString("ParticleRepresentation_TangibleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartStop_Start {
            get {
                return ResourceManager.GetString("StartStop_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StartStop_Stop {
            get {
                return ResourceManager.GetString("StartStop_Stop", resourceCulture);
            }
        }
    }
}
