//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSemantics.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSemantics.Utilities.NewNames", typeof(NewNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation change.
        /// </summary>
        public static string AnimationChange {
            get {
                return ResourceManager.GetString("AnimationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation condition.
        /// </summary>
        public static string AnimationCondition {
            get {
                return ResourceManager.GetString("AnimationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio change.
        /// </summary>
        public static string AudioChange {
            get {
                return ResourceManager.GetString("AudioChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio condition.
        /// </summary>
        public static string AudioCondition {
            get {
                return ResourceManager.GetString("AudioCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinematic.
        /// </summary>
        public static string Cinematic {
            get {
                return ResourceManager.GetString("Cinematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinematic change.
        /// </summary>
        public static string CinematicChange {
            get {
                return ResourceManager.GetString("CinematicChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinematic condition.
        /// </summary>
        public static string CinematicCondition {
            get {
                return ResourceManager.GetString("CinematicCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game filter.
        /// </summary>
        public static string GameFilter {
            get {
                return ResourceManager.GetString("GameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game filter change.
        /// </summary>
        public static string GameFilterChange {
            get {
                return ResourceManager.GetString("GameFilterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game filter condition.
        /// </summary>
        public static string GameFilterCondition {
            get {
                return ResourceManager.GetString("GameFilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game material.
        /// </summary>
        public static string GameMaterial {
            get {
                return ResourceManager.GetString("GameMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game material change.
        /// </summary>
        public static string GameMaterialChange {
            get {
                return ResourceManager.GetString("GameMaterialChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game material condition.
        /// </summary>
        public static string GameMaterialCondition {
            get {
                return ResourceManager.GetString("GameMaterialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game node.
        /// </summary>
        public static string GameNode {
            get {
                return ResourceManager.GetString("GameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game object.
        /// </summary>
        public static string GameObject {
            get {
                return ResourceManager.GetString("GameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon change.
        /// </summary>
        public static string IconChange {
            get {
                return ResourceManager.GetString("IconChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon condition.
        /// </summary>
        public static string IconCondition {
            get {
                return ResourceManager.GetString("IconCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model change.
        /// </summary>
        public static string ModelChange {
            get {
                return ResourceManager.GetString("ModelChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model condition.
        /// </summary>
        public static string ModelCondition {
            get {
                return ResourceManager.GetString("ModelCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle emitter.
        /// </summary>
        public static string ParticleEmitter {
            get {
                return ResourceManager.GetString("ParticleEmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle emitter change.
        /// </summary>
        public static string ParticleEmitterChange {
            get {
                return ResourceManager.GetString("ParticleEmitterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle emitter condition.
        /// </summary>
        public static string ParticleEmitterCondition {
            get {
                return ResourceManager.GetString("ParticleEmitterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle properties.
        /// </summary>
        public static string ParticleProperties {
            get {
                return ResourceManager.GetString("ParticleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle properties change.
        /// </summary>
        public static string ParticlePropertiesChange {
            get {
                return ResourceManager.GetString("ParticlePropertiesChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle properties condition.
        /// </summary>
        public static string ParticlePropertiesCondition {
            get {
                return ResourceManager.GetString("ParticlePropertiesCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script change.
        /// </summary>
        public static string ScriptChange {
            get {
                return ResourceManager.GetString("ScriptChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script condition.
        /// </summary>
        public static string ScriptCondition {
            get {
                return ResourceManager.GetString("ScriptCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite.
        /// </summary>
        public static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite change.
        /// </summary>
        public static string SpriteChange {
            get {
                return ResourceManager.GetString("SpriteChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite condition.
        /// </summary>
        public static string SpriteCondition {
            get {
                return ResourceManager.GetString("SpriteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
